// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createListing = `-- name: CreateListing :one
INSERT INTO listings (
    source_id, source_listing_id, url, first_seen_at, last_seen_at,
    status, consecutive_misses, dismissed, dismissed_reason, saved,
    title, description, price_cents, acres,
    address_line, city, county, state, postal_code,
    geom, photos,
    broker_name, broker_phone, broker_email,
    posted_at, source_updated_at,
    attr_water_frontage, attr_off_grid, attr_road_access,
    attr_power, attr_well, attr_septic, attr_property_type,
    attrs_extra, attrs_extraction
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14,
    $15, $16, $17, $18, $19,
    ST_GeomFromText($20::text, 4326), $21,
    $22, $23, $24,
    $25, $26,
    $27, $28, $29,
    $30, $31, $32, $33,
    $34, $35
)
RETURNING
    id, source_id, source_listing_id, url, first_seen_at, last_seen_at,
    status, consecutive_misses, dismissed, dismissed_reason, saved,
    title, description, price_cents, acres, price_per_acre_cents,
    address_line, city, county, state, postal_code,
    ST_AsText(geom) AS geom_wkt,
    photos, broker_name, broker_phone, broker_email, posted_at, source_updated_at,
    attr_water_frontage, attr_off_grid, attr_road_access, attr_power, attr_well, attr_septic,
    attr_property_type, attrs_extra, attrs_extraction
`

type CreateListingParams struct {
	SourceID          string
	SourceListingID   string
	Url               string
	FirstSeenAt       pgtype.Timestamptz
	LastSeenAt        pgtype.Timestamptz
	Status            string
	ConsecutiveMisses int32
	Dismissed         bool
	DismissedReason   pgtype.Text
	Saved             bool
	Title             pgtype.Text
	Description       pgtype.Text
	PriceCents        pgtype.Int8
	Acres             pgtype.Numeric
	AddressLine       pgtype.Text
	City              pgtype.Text
	County            pgtype.Text
	State             pgtype.Text
	PostalCode        pgtype.Text
	GeomWkt           pgtype.Text
	Photos            []string
	BrokerName        pgtype.Text
	BrokerPhone       pgtype.Text
	BrokerEmail       pgtype.Text
	PostedAt          pgtype.Timestamptz
	SourceUpdatedAt   pgtype.Timestamptz
	AttrWaterFrontage pgtype.Bool
	AttrOffGrid       pgtype.Bool
	AttrRoadAccess    pgtype.Text
	AttrPower         pgtype.Bool
	AttrWell          pgtype.Bool
	AttrSeptic        pgtype.Bool
	AttrPropertyType  pgtype.Text
	AttrsExtra        []byte
	AttrsExtraction   []byte
}

type CreateListingRow struct {
	ID                pgtype.UUID
	SourceID          string
	SourceListingID   string
	Url               string
	FirstSeenAt       pgtype.Timestamptz
	LastSeenAt        pgtype.Timestamptz
	Status            string
	ConsecutiveMisses int32
	Dismissed         bool
	DismissedReason   pgtype.Text
	Saved             bool
	Title             pgtype.Text
	Description       pgtype.Text
	PriceCents        pgtype.Int8
	Acres             pgtype.Numeric
	PricePerAcreCents pgtype.Int8
	AddressLine       pgtype.Text
	City              pgtype.Text
	County            pgtype.Text
	State             pgtype.Text
	PostalCode        pgtype.Text
	GeomWkt           interface{}
	Photos            []string
	BrokerName        pgtype.Text
	BrokerPhone       pgtype.Text
	BrokerEmail       pgtype.Text
	PostedAt          pgtype.Timestamptz
	SourceUpdatedAt   pgtype.Timestamptz
	AttrWaterFrontage pgtype.Bool
	AttrOffGrid       pgtype.Bool
	AttrRoadAccess    pgtype.Text
	AttrPower         pgtype.Bool
	AttrWell          pgtype.Bool
	AttrSeptic        pgtype.Bool
	AttrPropertyType  pgtype.Text
	AttrsExtra        []byte
	AttrsExtraction   []byte
}

func (q *Queries) CreateListing(ctx context.Context, arg CreateListingParams) (CreateListingRow, error) {
	row := q.db.QueryRow(ctx, createListing,
		arg.SourceID,
		arg.SourceListingID,
		arg.Url,
		arg.FirstSeenAt,
		arg.LastSeenAt,
		arg.Status,
		arg.ConsecutiveMisses,
		arg.Dismissed,
		arg.DismissedReason,
		arg.Saved,
		arg.Title,
		arg.Description,
		arg.PriceCents,
		arg.Acres,
		arg.AddressLine,
		arg.City,
		arg.County,
		arg.State,
		arg.PostalCode,
		arg.GeomWkt,
		arg.Photos,
		arg.BrokerName,
		arg.BrokerPhone,
		arg.BrokerEmail,
		arg.PostedAt,
		arg.SourceUpdatedAt,
		arg.AttrWaterFrontage,
		arg.AttrOffGrid,
		arg.AttrRoadAccess,
		arg.AttrPower,
		arg.AttrWell,
		arg.AttrSeptic,
		arg.AttrPropertyType,
		arg.AttrsExtra,
		arg.AttrsExtraction,
	)
	var i CreateListingRow
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.SourceListingID,
		&i.Url,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Status,
		&i.ConsecutiveMisses,
		&i.Dismissed,
		&i.DismissedReason,
		&i.Saved,
		&i.Title,
		&i.Description,
		&i.PriceCents,
		&i.Acres,
		&i.PricePerAcreCents,
		&i.AddressLine,
		&i.City,
		&i.County,
		&i.State,
		&i.PostalCode,
		&i.GeomWkt,
		&i.Photos,
		&i.BrokerName,
		&i.BrokerPhone,
		&i.BrokerEmail,
		&i.PostedAt,
		&i.SourceUpdatedAt,
		&i.AttrWaterFrontage,
		&i.AttrOffGrid,
		&i.AttrRoadAccess,
		&i.AttrPower,
		&i.AttrWell,
		&i.AttrSeptic,
		&i.AttrPropertyType,
		&i.AttrsExtra,
		&i.AttrsExtraction,
	)
	return i, err
}

const createListingSnapshot = `-- name: CreateListingSnapshot :one
INSERT INTO listing_snapshots (
    listing_id, raw_fetch_id, captured_at,
    price_cents, acres, status, title, description,
    structured_attrs, diff
) VALUES (
    $1::uuid, $2, $3,
    $4, $5, $6,
    $7, $8,
    $9, $10
)
RETURNING id, listing_id, raw_fetch_id, captured_at, price_cents, acres, status, title, description, structured_attrs, diff
`

type CreateListingSnapshotParams struct {
	ListingID       pgtype.UUID
	RawFetchID      int64
	CapturedAt      pgtype.Timestamptz
	PriceCents      pgtype.Int8
	Acres           pgtype.Numeric
	Status          pgtype.Text
	Title           pgtype.Text
	Description     pgtype.Text
	StructuredAttrs []byte
	Diff            []byte
}

func (q *Queries) CreateListingSnapshot(ctx context.Context, arg CreateListingSnapshotParams) (ListingSnapshot, error) {
	row := q.db.QueryRow(ctx, createListingSnapshot,
		arg.ListingID,
		arg.RawFetchID,
		arg.CapturedAt,
		arg.PriceCents,
		arg.Acres,
		arg.Status,
		arg.Title,
		arg.Description,
		arg.StructuredAttrs,
		arg.Diff,
	)
	var i ListingSnapshot
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.RawFetchID,
		&i.CapturedAt,
		&i.PriceCents,
		&i.Acres,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.StructuredAttrs,
		&i.Diff,
	)
	return i, err
}

const createParseAttempt = `-- name: CreateParseAttempt :one
INSERT INTO parse_attempts (raw_fetch_id, parser_version, attempted_at, outcome, error_message, snapshot_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, raw_fetch_id, parser_version, attempted_at, outcome, error_message, snapshot_id
`

type CreateParseAttemptParams struct {
	RawFetchID    int64
	ParserVersion string
	AttemptedAt   pgtype.Timestamptz
	Outcome       string
	ErrorMessage  pgtype.Text
	SnapshotID    pgtype.Int8
}

func (q *Queries) CreateParseAttempt(ctx context.Context, arg CreateParseAttemptParams) (ParseAttempt, error) {
	row := q.db.QueryRow(ctx, createParseAttempt,
		arg.RawFetchID,
		arg.ParserVersion,
		arg.AttemptedAt,
		arg.Outcome,
		arg.ErrorMessage,
		arg.SnapshotID,
	)
	var i ParseAttempt
	err := row.Scan(
		&i.ID,
		&i.RawFetchID,
		&i.ParserVersion,
		&i.AttemptedAt,
		&i.Outcome,
		&i.ErrorMessage,
		&i.SnapshotID,
	)
	return i, err
}

const createPriceChange = `-- name: CreatePriceChange :one
INSERT INTO price_changes (
    listing_id, changed_at, old_price_cents, new_price_cents, snapshot_id
) VALUES (
    $1::uuid, $2, $3, $4, $5
)
RETURNING id, listing_id, changed_at, old_price_cents, new_price_cents, delta_cents, snapshot_id
`

type CreatePriceChangeParams struct {
	ListingID     pgtype.UUID
	ChangedAt     pgtype.Timestamptz
	OldPriceCents pgtype.Int8
	NewPriceCents int64
	SnapshotID    pgtype.Int8
}

func (q *Queries) CreatePriceChange(ctx context.Context, arg CreatePriceChangeParams) (PriceChange, error) {
	row := q.db.QueryRow(ctx, createPriceChange,
		arg.ListingID,
		arg.ChangedAt,
		arg.OldPriceCents,
		arg.NewPriceCents,
		arg.SnapshotID,
	)
	var i PriceChange
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.ChangedAt,
		&i.OldPriceCents,
		&i.NewPriceCents,
		&i.DeltaCents,
		&i.SnapshotID,
	)
	return i, err
}

const getListingByID = `-- name: GetListingByID :one
SELECT
    id, source_id, source_listing_id, url, first_seen_at, last_seen_at,
    status, consecutive_misses, dismissed, dismissed_reason, saved,
    title, description, price_cents, acres, price_per_acre_cents,
    address_line, city, county, state, postal_code,
    ST_AsText(geom) AS geom_wkt,
    photos, broker_name, broker_phone, broker_email, posted_at, source_updated_at,
    attr_water_frontage, attr_off_grid, attr_road_access, attr_power, attr_well, attr_septic,
    attr_property_type, attrs_extra, attrs_extraction
FROM listings
WHERE id = $1::uuid
`

type GetListingByIDRow struct {
	ID                pgtype.UUID
	SourceID          string
	SourceListingID   string
	Url               string
	FirstSeenAt       pgtype.Timestamptz
	LastSeenAt        pgtype.Timestamptz
	Status            string
	ConsecutiveMisses int32
	Dismissed         bool
	DismissedReason   pgtype.Text
	Saved             bool
	Title             pgtype.Text
	Description       pgtype.Text
	PriceCents        pgtype.Int8
	Acres             pgtype.Numeric
	PricePerAcreCents pgtype.Int8
	AddressLine       pgtype.Text
	City              pgtype.Text
	County            pgtype.Text
	State             pgtype.Text
	PostalCode        pgtype.Text
	GeomWkt           interface{}
	Photos            []string
	BrokerName        pgtype.Text
	BrokerPhone       pgtype.Text
	BrokerEmail       pgtype.Text
	PostedAt          pgtype.Timestamptz
	SourceUpdatedAt   pgtype.Timestamptz
	AttrWaterFrontage pgtype.Bool
	AttrOffGrid       pgtype.Bool
	AttrRoadAccess    pgtype.Text
	AttrPower         pgtype.Bool
	AttrWell          pgtype.Bool
	AttrSeptic        pgtype.Bool
	AttrPropertyType  pgtype.Text
	AttrsExtra        []byte
	AttrsExtraction   []byte
}

func (q *Queries) GetListingByID(ctx context.Context, id pgtype.UUID) (GetListingByIDRow, error) {
	row := q.db.QueryRow(ctx, getListingByID, id)
	var i GetListingByIDRow
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.SourceListingID,
		&i.Url,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Status,
		&i.ConsecutiveMisses,
		&i.Dismissed,
		&i.DismissedReason,
		&i.Saved,
		&i.Title,
		&i.Description,
		&i.PriceCents,
		&i.Acres,
		&i.PricePerAcreCents,
		&i.AddressLine,
		&i.City,
		&i.County,
		&i.State,
		&i.PostalCode,
		&i.GeomWkt,
		&i.Photos,
		&i.BrokerName,
		&i.BrokerPhone,
		&i.BrokerEmail,
		&i.PostedAt,
		&i.SourceUpdatedAt,
		&i.AttrWaterFrontage,
		&i.AttrOffGrid,
		&i.AttrRoadAccess,
		&i.AttrPower,
		&i.AttrWell,
		&i.AttrSeptic,
		&i.AttrPropertyType,
		&i.AttrsExtra,
		&i.AttrsExtraction,
	)
	return i, err
}

const getListingBySource = `-- name: GetListingBySource :one
SELECT
    id, source_id, source_listing_id, url, first_seen_at, last_seen_at,
    status, consecutive_misses, dismissed, dismissed_reason, saved,
    title, description, price_cents, acres, price_per_acre_cents,
    address_line, city, county, state, postal_code,
    ST_AsText(geom) AS geom_wkt,
    photos, broker_name, broker_phone, broker_email, posted_at, source_updated_at,
    attr_water_frontage, attr_off_grid, attr_road_access, attr_power, attr_well, attr_septic,
    attr_property_type, attrs_extra, attrs_extraction
FROM listings
WHERE source_id = $1 AND source_listing_id = $2
`

type GetListingBySourceParams struct {
	SourceID        string
	SourceListingID string
}

type GetListingBySourceRow struct {
	ID                pgtype.UUID
	SourceID          string
	SourceListingID   string
	Url               string
	FirstSeenAt       pgtype.Timestamptz
	LastSeenAt        pgtype.Timestamptz
	Status            string
	ConsecutiveMisses int32
	Dismissed         bool
	DismissedReason   pgtype.Text
	Saved             bool
	Title             pgtype.Text
	Description       pgtype.Text
	PriceCents        pgtype.Int8
	Acres             pgtype.Numeric
	PricePerAcreCents pgtype.Int8
	AddressLine       pgtype.Text
	City              pgtype.Text
	County            pgtype.Text
	State             pgtype.Text
	PostalCode        pgtype.Text
	GeomWkt           interface{}
	Photos            []string
	BrokerName        pgtype.Text
	BrokerPhone       pgtype.Text
	BrokerEmail       pgtype.Text
	PostedAt          pgtype.Timestamptz
	SourceUpdatedAt   pgtype.Timestamptz
	AttrWaterFrontage pgtype.Bool
	AttrOffGrid       pgtype.Bool
	AttrRoadAccess    pgtype.Text
	AttrPower         pgtype.Bool
	AttrWell          pgtype.Bool
	AttrSeptic        pgtype.Bool
	AttrPropertyType  pgtype.Text
	AttrsExtra        []byte
	AttrsExtraction   []byte
}

func (q *Queries) GetListingBySource(ctx context.Context, arg GetListingBySourceParams) (GetListingBySourceRow, error) {
	row := q.db.QueryRow(ctx, getListingBySource, arg.SourceID, arg.SourceListingID)
	var i GetListingBySourceRow
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.SourceListingID,
		&i.Url,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Status,
		&i.ConsecutiveMisses,
		&i.Dismissed,
		&i.DismissedReason,
		&i.Saved,
		&i.Title,
		&i.Description,
		&i.PriceCents,
		&i.Acres,
		&i.PricePerAcreCents,
		&i.AddressLine,
		&i.City,
		&i.County,
		&i.State,
		&i.PostalCode,
		&i.GeomWkt,
		&i.Photos,
		&i.BrokerName,
		&i.BrokerPhone,
		&i.BrokerEmail,
		&i.PostedAt,
		&i.SourceUpdatedAt,
		&i.AttrWaterFrontage,
		&i.AttrOffGrid,
		&i.AttrRoadAccess,
		&i.AttrPower,
		&i.AttrWell,
		&i.AttrSeptic,
		&i.AttrPropertyType,
		&i.AttrsExtra,
		&i.AttrsExtraction,
	)
	return i, err
}

const listPriceChangesByListing = `-- name: ListPriceChangesByListing :many
SELECT id, listing_id, changed_at, old_price_cents, new_price_cents, delta_cents, snapshot_id
FROM price_changes
WHERE listing_id = $1::uuid
ORDER BY changed_at DESC
`

func (q *Queries) ListPriceChangesByListing(ctx context.Context, listingID pgtype.UUID) ([]PriceChange, error) {
	rows, err := q.db.Query(ctx, listPriceChangesByListing, listingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PriceChange
	for rows.Next() {
		var i PriceChange
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.ChangedAt,
			&i.OldPriceCents,
			&i.NewPriceCents,
			&i.DeltaCents,
			&i.SnapshotID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotsByListing = `-- name: ListSnapshotsByListing :many
SELECT id, listing_id, raw_fetch_id, captured_at, price_cents, acres, status, title, description, structured_attrs, diff FROM listing_snapshots
WHERE listing_id = $1::uuid
ORDER BY captured_at DESC
`

func (q *Queries) ListSnapshotsByListing(ctx context.Context, listingID pgtype.UUID) ([]ListingSnapshot, error) {
	rows, err := q.db.Query(ctx, listSnapshotsByListing, listingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListingSnapshot
	for rows.Next() {
		var i ListingSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.RawFetchID,
			&i.CapturedAt,
			&i.PriceCents,
			&i.Acres,
			&i.Status,
			&i.Title,
			&i.Description,
			&i.StructuredAttrs,
			&i.Diff,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateListing = `-- name: UpdateListing :exec
UPDATE listings SET
    url                = $1,
    last_seen_at       = $2,
    status             = $3,
    consecutive_misses = $4,
    dismissed          = $5,
    dismissed_reason   = $6,
    saved              = $7,
    title              = $8,
    description        = $9,
    price_cents        = $10,
    acres              = $11,
    address_line       = $12,
    city               = $13,
    county             = $14,
    state              = $15,
    postal_code        = $16,
    geom               = ST_GeomFromText($17::text, 4326),
    photos             = $18,
    broker_name        = $19,
    broker_phone       = $20,
    broker_email       = $21,
    posted_at          = $22,
    source_updated_at  = $23,
    attr_water_frontage = $24,
    attr_off_grid      = $25,
    attr_road_access   = $26,
    attr_power         = $27,
    attr_well          = $28,
    attr_septic        = $29,
    attr_property_type = $30,
    attrs_extra        = $31,
    attrs_extraction   = $32
WHERE id = $33::uuid
`

type UpdateListingParams struct {
	Url               string
	LastSeenAt        pgtype.Timestamptz
	Status            string
	ConsecutiveMisses int32
	Dismissed         bool
	DismissedReason   pgtype.Text
	Saved             bool
	Title             pgtype.Text
	Description       pgtype.Text
	PriceCents        pgtype.Int8
	Acres             pgtype.Numeric
	AddressLine       pgtype.Text
	City              pgtype.Text
	County            pgtype.Text
	State             pgtype.Text
	PostalCode        pgtype.Text
	GeomWkt           pgtype.Text
	Photos            []string
	BrokerName        pgtype.Text
	BrokerPhone       pgtype.Text
	BrokerEmail       pgtype.Text
	PostedAt          pgtype.Timestamptz
	SourceUpdatedAt   pgtype.Timestamptz
	AttrWaterFrontage pgtype.Bool
	AttrOffGrid       pgtype.Bool
	AttrRoadAccess    pgtype.Text
	AttrPower         pgtype.Bool
	AttrWell          pgtype.Bool
	AttrSeptic        pgtype.Bool
	AttrPropertyType  pgtype.Text
	AttrsExtra        []byte
	AttrsExtraction   []byte
	ID                pgtype.UUID
}

func (q *Queries) UpdateListing(ctx context.Context, arg UpdateListingParams) error {
	_, err := q.db.Exec(ctx, updateListing,
		arg.Url,
		arg.LastSeenAt,
		arg.Status,
		arg.ConsecutiveMisses,
		arg.Dismissed,
		arg.DismissedReason,
		arg.Saved,
		arg.Title,
		arg.Description,
		arg.PriceCents,
		arg.Acres,
		arg.AddressLine,
		arg.City,
		arg.County,
		arg.State,
		arg.PostalCode,
		arg.GeomWkt,
		arg.Photos,
		arg.BrokerName,
		arg.BrokerPhone,
		arg.BrokerEmail,
		arg.PostedAt,
		arg.SourceUpdatedAt,
		arg.AttrWaterFrontage,
		arg.AttrOffGrid,
		arg.AttrRoadAccess,
		arg.AttrPower,
		arg.AttrWell,
		arg.AttrSeptic,
		arg.AttrPropertyType,
		arg.AttrsExtra,
		arg.AttrsExtraction,
		arg.ID,
	)
	return err
}
