// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Listing struct {
	ID                pgtype.UUID
	SourceID          string
	SourceListingID   string
	Url               string
	FirstSeenAt       pgtype.Timestamptz
	LastSeenAt        pgtype.Timestamptz
	Status            string
	ConsecutiveMisses int32
	Dismissed         bool
	DismissedReason   pgtype.Text
	Saved             bool
	Title             pgtype.Text
	Description       pgtype.Text
	PriceCents        pgtype.Int8
	Acres             pgtype.Numeric
	PricePerAcreCents pgtype.Int8
	AddressLine       pgtype.Text
	City              pgtype.Text
	County            pgtype.Text
	State             pgtype.Text
	PostalCode        pgtype.Text
	Geom              pgtype.Text
	Photos            []string
	BrokerName        pgtype.Text
	BrokerPhone       pgtype.Text
	BrokerEmail       pgtype.Text
	PostedAt          pgtype.Timestamptz
	SourceUpdatedAt   pgtype.Timestamptz
	AttrWaterFrontage pgtype.Bool
	AttrOffGrid       pgtype.Bool
	AttrRoadAccess    pgtype.Text
	AttrPower         pgtype.Bool
	AttrWell          pgtype.Bool
	AttrSeptic        pgtype.Bool
	AttrPropertyType  pgtype.Text
	AttrsExtra        []byte
	AttrsExtraction   []byte
}

type ListingSnapshot struct {
	ID              int64
	ListingID       pgtype.UUID
	RawFetchID      int64
	CapturedAt      pgtype.Timestamptz
	PriceCents      pgtype.Int8
	Acres           pgtype.Numeric
	Status          pgtype.Text
	Title           pgtype.Text
	Description     pgtype.Text
	StructuredAttrs []byte
	Diff            []byte
}

type ParseAttempt struct {
	ID            int64
	RawFetchID    int64
	ParserVersion string
	AttemptedAt   pgtype.Timestamptz
	Outcome       string
	ErrorMessage  pgtype.Text
	SnapshotID    pgtype.Int8
}

type PriceChange struct {
	ID            int64
	ListingID     pgtype.UUID
	ChangedAt     pgtype.Timestamptz
	OldPriceCents pgtype.Int8
	NewPriceCents int64
	DeltaCents    pgtype.Int8
	SnapshotID    pgtype.Int8
}

type RawFetch struct {
	ID              int64
	SourceID        string
	SourceListingID string
	ScrapeRunID     pgtype.Int8
	Url             string
	FetchedAt       pgtype.Timestamptz
	StatusCode      int32
	ContentType     pgtype.Text
	Body            []byte
	BodySha256      []byte
	HeadersJson     []byte
}

type ScrapeRun struct {
	ID              int64
	SourceID        string
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	Status          string
	DiscoveredCount pgtype.Int4
	FetchedCount    pgtype.Int4
	ParsedCount     pgtype.Int4
	ErrorCount      pgtype.Int4
	ErrorSample     pgtype.Text
	Notes           pgtype.Text
}

type Source struct {
	ID                             string
	DisplayName                    string
	BaseUrl                        string
	Enabled                        bool
	RateLimitMs                    int32
	Concurrency                    int32
	UserAgent                      string
	RespectRobots                  bool
	AbsenceDaysBeforeStale         int32
	AbsenceDaysBeforeInactive      int32
	ConsecutiveMissedRunsThreshold int32
	MinResultRatioForInactivation  pgtype.Numeric
	LastRunAt                      pgtype.Timestamptz
	NextRunAt                      pgtype.Timestamptz
	Notes                          pgtype.Text
}
