// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: source.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRawFetch = `-- name: CreateRawFetch :one
INSERT INTO raw_fetches (
    source_id, source_listing_id, scrape_run_id, url,
    fetched_at, status_code, content_type,
    body, body_sha256, headers_json
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10
)
RETURNING id, source_id, source_listing_id, scrape_run_id, url, fetched_at, status_code, content_type, body, body_sha256, headers_json
`

type CreateRawFetchParams struct {
	SourceID        string
	SourceListingID string
	ScrapeRunID     pgtype.Int8
	Url             string
	FetchedAt       pgtype.Timestamptz
	StatusCode      int32
	ContentType     pgtype.Text
	Body            []byte
	BodySha256      []byte
	HeadersJson     []byte
}

func (q *Queries) CreateRawFetch(ctx context.Context, arg CreateRawFetchParams) (RawFetch, error) {
	row := q.db.QueryRow(ctx, createRawFetch,
		arg.SourceID,
		arg.SourceListingID,
		arg.ScrapeRunID,
		arg.Url,
		arg.FetchedAt,
		arg.StatusCode,
		arg.ContentType,
		arg.Body,
		arg.BodySha256,
		arg.HeadersJson,
	)
	var i RawFetch
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.SourceListingID,
		&i.ScrapeRunID,
		&i.Url,
		&i.FetchedAt,
		&i.StatusCode,
		&i.ContentType,
		&i.Body,
		&i.BodySha256,
		&i.HeadersJson,
	)
	return i, err
}

const createScrapeRun = `-- name: CreateScrapeRun :one
INSERT INTO scrape_runs (
    source_id, started_at, finished_at, status,
    discovered_count, fetched_count, parsed_count, error_count,
    error_sample, notes
) VALUES (
    $1, $2, $3, $4,
    $5, $6,
    $7, $8,
    $9, $10
)
RETURNING id, source_id, started_at, finished_at, status, discovered_count, fetched_count, parsed_count, error_count, error_sample, notes
`

type CreateScrapeRunParams struct {
	SourceID        string
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	Status          string
	DiscoveredCount pgtype.Int4
	FetchedCount    pgtype.Int4
	ParsedCount     pgtype.Int4
	ErrorCount      pgtype.Int4
	ErrorSample     pgtype.Text
	Notes           pgtype.Text
}

func (q *Queries) CreateScrapeRun(ctx context.Context, arg CreateScrapeRunParams) (ScrapeRun, error) {
	row := q.db.QueryRow(ctx, createScrapeRun,
		arg.SourceID,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Status,
		arg.DiscoveredCount,
		arg.FetchedCount,
		arg.ParsedCount,
		arg.ErrorCount,
		arg.ErrorSample,
		arg.Notes,
	)
	var i ScrapeRun
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.DiscoveredCount,
		&i.FetchedCount,
		&i.ParsedCount,
		&i.ErrorCount,
		&i.ErrorSample,
		&i.Notes,
	)
	return i, err
}

const createSource = `-- name: CreateSource :one
INSERT INTO sources (
    id, display_name, base_url, enabled, rate_limit_ms, concurrency,
    user_agent, respect_robots, absence_days_before_stale,
    absence_days_before_inactive, consecutive_missed_runs_threshold,
    min_result_ratio_for_inactivation, last_run_at, next_run_at, notes
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9,
    $10, $11,
    $12, $13, $14, $15
)
RETURNING id, display_name, base_url, enabled, rate_limit_ms, concurrency, user_agent, respect_robots, absence_days_before_stale, absence_days_before_inactive, consecutive_missed_runs_threshold, min_result_ratio_for_inactivation, last_run_at, next_run_at, notes
`

type CreateSourceParams struct {
	ID                             string
	DisplayName                    string
	BaseUrl                        string
	Enabled                        bool
	RateLimitMs                    int32
	Concurrency                    int32
	UserAgent                      string
	RespectRobots                  bool
	AbsenceDaysBeforeStale         int32
	AbsenceDaysBeforeInactive      int32
	ConsecutiveMissedRunsThreshold int32
	MinResultRatioForInactivation  pgtype.Numeric
	LastRunAt                      pgtype.Timestamptz
	NextRunAt                      pgtype.Timestamptz
	Notes                          pgtype.Text
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, createSource,
		arg.ID,
		arg.DisplayName,
		arg.BaseUrl,
		arg.Enabled,
		arg.RateLimitMs,
		arg.Concurrency,
		arg.UserAgent,
		arg.RespectRobots,
		arg.AbsenceDaysBeforeStale,
		arg.AbsenceDaysBeforeInactive,
		arg.ConsecutiveMissedRunsThreshold,
		arg.MinResultRatioForInactivation,
		arg.LastRunAt,
		arg.NextRunAt,
		arg.Notes,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.BaseUrl,
		&i.Enabled,
		&i.RateLimitMs,
		&i.Concurrency,
		&i.UserAgent,
		&i.RespectRobots,
		&i.AbsenceDaysBeforeStale,
		&i.AbsenceDaysBeforeInactive,
		&i.ConsecutiveMissedRunsThreshold,
		&i.MinResultRatioForInactivation,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.Notes,
	)
	return i, err
}

const getRawFetchByID = `-- name: GetRawFetchByID :one
SELECT id, source_id, source_listing_id, scrape_run_id, url, fetched_at, status_code, content_type, body, body_sha256, headers_json FROM raw_fetches WHERE id = $1
`

func (q *Queries) GetRawFetchByID(ctx context.Context, id int64) (RawFetch, error) {
	row := q.db.QueryRow(ctx, getRawFetchByID, id)
	var i RawFetch
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.SourceListingID,
		&i.ScrapeRunID,
		&i.Url,
		&i.FetchedAt,
		&i.StatusCode,
		&i.ContentType,
		&i.Body,
		&i.BodySha256,
		&i.HeadersJson,
	)
	return i, err
}

const getScrapeRunByID = `-- name: GetScrapeRunByID :one
SELECT id, source_id, started_at, finished_at, status, discovered_count, fetched_count, parsed_count, error_count, error_sample, notes FROM scrape_runs WHERE id = $1
`

func (q *Queries) GetScrapeRunByID(ctx context.Context, id int64) (ScrapeRun, error) {
	row := q.db.QueryRow(ctx, getScrapeRunByID, id)
	var i ScrapeRun
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.DiscoveredCount,
		&i.FetchedCount,
		&i.ParsedCount,
		&i.ErrorCount,
		&i.ErrorSample,
		&i.Notes,
	)
	return i, err
}

const getSourceByID = `-- name: GetSourceByID :one
SELECT id, display_name, base_url, enabled, rate_limit_ms, concurrency, user_agent, respect_robots, absence_days_before_stale, absence_days_before_inactive, consecutive_missed_runs_threshold, min_result_ratio_for_inactivation, last_run_at, next_run_at, notes FROM sources WHERE id = $1
`

func (q *Queries) GetSourceByID(ctx context.Context, id string) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceByID, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.BaseUrl,
		&i.Enabled,
		&i.RateLimitMs,
		&i.Concurrency,
		&i.UserAgent,
		&i.RespectRobots,
		&i.AbsenceDaysBeforeStale,
		&i.AbsenceDaysBeforeInactive,
		&i.ConsecutiveMissedRunsThreshold,
		&i.MinResultRatioForInactivation,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.Notes,
	)
	return i, err
}

const listRawFetchesByListing = `-- name: ListRawFetchesByListing :many
SELECT id, source_id, source_listing_id, scrape_run_id, url, fetched_at, status_code, content_type, body, body_sha256, headers_json FROM raw_fetches
WHERE source_id = $1 AND source_listing_id = $2
ORDER BY fetched_at DESC
`

type ListRawFetchesByListingParams struct {
	SourceID        string
	SourceListingID string
}

func (q *Queries) ListRawFetchesByListing(ctx context.Context, arg ListRawFetchesByListingParams) ([]RawFetch, error) {
	rows, err := q.db.Query(ctx, listRawFetchesByListing, arg.SourceID, arg.SourceListingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RawFetch
	for rows.Next() {
		var i RawFetch
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.SourceListingID,
			&i.ScrapeRunID,
			&i.Url,
			&i.FetchedAt,
			&i.StatusCode,
			&i.ContentType,
			&i.Body,
			&i.BodySha256,
			&i.HeadersJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScrapeRunsBySource = `-- name: ListScrapeRunsBySource :many
SELECT id, source_id, started_at, finished_at, status, discovered_count, fetched_count, parsed_count, error_count, error_sample, notes FROM scrape_runs
WHERE source_id = $1
ORDER BY started_at DESC
LIMIT $2::int
`

type ListScrapeRunsBySourceParams struct {
	SourceID string
	Lim      int32
}

func (q *Queries) ListScrapeRunsBySource(ctx context.Context, arg ListScrapeRunsBySourceParams) ([]ScrapeRun, error) {
	rows, err := q.db.Query(ctx, listScrapeRunsBySource, arg.SourceID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScrapeRun
	for rows.Next() {
		var i ScrapeRun
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.DiscoveredCount,
			&i.FetchedCount,
			&i.ParsedCount,
			&i.ErrorCount,
			&i.ErrorSample,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSources = `-- name: ListSources :many
SELECT id, display_name, base_url, enabled, rate_limit_ms, concurrency, user_agent, respect_robots, absence_days_before_stale, absence_days_before_inactive, consecutive_missed_runs_threshold, min_result_ratio_for_inactivation, last_run_at, next_run_at, notes FROM sources ORDER BY id
`

func (q *Queries) ListSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.BaseUrl,
			&i.Enabled,
			&i.RateLimitMs,
			&i.Concurrency,
			&i.UserAgent,
			&i.RespectRobots,
			&i.AbsenceDaysBeforeStale,
			&i.AbsenceDaysBeforeInactive,
			&i.ConsecutiveMissedRunsThreshold,
			&i.MinResultRatioForInactivation,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScrapeRun = `-- name: UpdateScrapeRun :exec
UPDATE scrape_runs SET
    finished_at      = $1,
    status           = $2,
    discovered_count = $3,
    fetched_count    = $4,
    parsed_count     = $5,
    error_count      = $6,
    error_sample     = $7,
    notes            = $8
WHERE id = $9
`

type UpdateScrapeRunParams struct {
	FinishedAt      pgtype.Timestamptz
	Status          string
	DiscoveredCount pgtype.Int4
	FetchedCount    pgtype.Int4
	ParsedCount     pgtype.Int4
	ErrorCount      pgtype.Int4
	ErrorSample     pgtype.Text
	Notes           pgtype.Text
	ID              int64
}

func (q *Queries) UpdateScrapeRun(ctx context.Context, arg UpdateScrapeRunParams) error {
	_, err := q.db.Exec(ctx, updateScrapeRun,
		arg.FinishedAt,
		arg.Status,
		arg.DiscoveredCount,
		arg.FetchedCount,
		arg.ParsedCount,
		arg.ErrorCount,
		arg.ErrorSample,
		arg.Notes,
		arg.ID,
	)
	return err
}

const updateSource = `-- name: UpdateSource :exec
UPDATE sources SET
    display_name                      = $1,
    base_url                          = $2,
    enabled                           = $3,
    rate_limit_ms                     = $4,
    concurrency                       = $5,
    user_agent                        = $6,
    respect_robots                    = $7,
    absence_days_before_stale         = $8,
    absence_days_before_inactive      = $9,
    consecutive_missed_runs_threshold = $10,
    min_result_ratio_for_inactivation = $11,
    last_run_at                       = $12,
    next_run_at                       = $13,
    notes                             = $14
WHERE id = $15
`

type UpdateSourceParams struct {
	DisplayName                    string
	BaseUrl                        string
	Enabled                        bool
	RateLimitMs                    int32
	Concurrency                    int32
	UserAgent                      string
	RespectRobots                  bool
	AbsenceDaysBeforeStale         int32
	AbsenceDaysBeforeInactive      int32
	ConsecutiveMissedRunsThreshold int32
	MinResultRatioForInactivation  pgtype.Numeric
	LastRunAt                      pgtype.Timestamptz
	NextRunAt                      pgtype.Timestamptz
	Notes                          pgtype.Text
	ID                             string
}

func (q *Queries) UpdateSource(ctx context.Context, arg UpdateSourceParams) error {
	_, err := q.db.Exec(ctx, updateSource,
		arg.DisplayName,
		arg.BaseUrl,
		arg.Enabled,
		arg.RateLimitMs,
		arg.Concurrency,
		arg.UserAgent,
		arg.RespectRobots,
		arg.AbsenceDaysBeforeStale,
		arg.AbsenceDaysBeforeInactive,
		arg.ConsecutiveMissedRunsThreshold,
		arg.MinResultRatioForInactivation,
		arg.LastRunAt,
		arg.NextRunAt,
		arg.Notes,
		arg.ID,
	)
	return err
}
